version: "3.9"

services:
  app:
    build: .
    image: docker.rhardih.io/burgonomic
    env_file: .env
    networks:
      - default
      - traefik-public
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 64M
        reservations:
          cpus: '0.1'
          memory: 32M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.burgonomic-http.rule=Host(`burgonomic.rhardih.io`)
        - traefik.http.routers.burgonomic-http.entrypoints=http
        - traefik.http.routers.burgonomic-http.middlewares=https-redirect
        - traefik.http.routers.burgonomic-https.rule=Host(`burgonomic.rhardih.io`)
        - traefik.http.routers.burgonomic-https.entrypoints=https
        - traefik.http.routers.burgonomic-https.tls=true
        - traefik.http.routers.burgonomic-https.tls.certresolver=le
        - traefik.http.services.burgonomic.loadbalancer.server.port=8080

networks:
  traefik-public:
    external: true
